### ISSUE TITLE
What is the diffrence from 'Screenshot To Code GPT'

### ISSUE THREAD

**Issue by tiger2014** [abi/screenshot-to-code#127]
You said in the ReadMe that this project will use openai's api key, and there had been a 'Screenshot To Code GPT' in ChatGPT, I want to know the diffrence between them. 

Thanks!

**Comment by abi** [comment]
The quality of the outputs should be better with this project because we have more control in the API over temperature, max tokens settings, etc. This project also generates placeholder images with DALL-E, and provides a live preview + live code editing. You can also export choose which framework to export code in: React, Tailwind, Bootstrap.
