### ISSUE TITLE
API as a service?

### ISSUE THREAD

**Issue by DiTo97** [abi/screenshot-to-code#213]
Hi @abi,

I have been working on an AI-driven automatic website generation platform which looks roughly like the following:
1. users submit ideas on website topics (e.g., "smart mailboxes");
2. a language model and a text-to-image model work together generating website screenshot proposals;
3. users may select the preferred proposal or discard them all going back to step 2.;
4. users may refine the preferred proposal going back to step 2.;
5. users finalize the proposal with a model generating the website code in the preferred JS framework.

Thus far, I am keeping things simple allowing only single-page webapps (SPAs) and completing step 5. manually on the [website](https://screenshottocode.com/).

Are there any plans of exposing the screenshot-to-code website functionality as a REST API?

**Comment by abi** [comment]
@DiTo97 hey, that's a really cool idea. I'm not planning to support an API at the moment but I'm interested in hearing if others have a similar use case. For now, since this is an open source project, you can deploy the backend to something like Render (which is what I use) and host the API yourself. Does that work for you?

**Comment by abi** [comment]
Please do share it. That would be great!
