### ISSUE TITLE
Add a button to convert code to React and Vite

### ISSUE THREAD

**Issue by abi** [abi/screenshot-to-code#24]
I think it'll work better to convert code to React or Vite using gpt4 turbo rather than generate the code in React or Vite in the first place.

But both approaches are worth experimenting with.

**Comment by Kunhe-tes** [comment]
Does having the ability to convert code to React or Vite mean that some programmers will lose their jobs?

**Comment by clean99** [comment]
Since the page generated by now is in a single HTML file, it is hard to maintain and not reusable. By adding a React section, we can take advantage of the modularity of React.

Here is my initiative:
1. Add a React code section, which prompts GPT to generate React code instead of HTML code.
2. Embed [codesandbox](https://codesandbox.io/docs/learn) as IDE of React, so that we can display and edit react code in real time.
3. Prompt GPT to separate the page into proper components and put them in the correct directory of IDE so that the structure of the code is more reusable.

**Comment by abi** [comment]
Getting GPT to deal with multiple files is a hard problem that's not solved reliably. Getting a single file/page react app would be a good start.

**Comment by clean99** [comment]
> Getting GPT to deal with multiple files is a hard problem that's not solved reliably. Getting a single file/page react app would be a good start.

Thanks for replying, will give it a try tmr.

**Comment by H5DevHoward** [comment]
> Does having the ability to convert code to React or Vite mean that some programmers will lose their jobs?

Pessimistically, I think it's just a matter of time

**Comment by abi** [comment]
React is done. Closing in favor of https://github.com/abi/screenshot-to-code/issues/96
