### ISSUE TITLE
How many tokens are probably consumed or how much it will cost to generate a table page.

### ISSUE THREAD

**Issue by Thea1211** [abi/screenshot-to-code#310]
How many tokens are probably consumed or how much it will cost to generate a table page. Is there a rough amount / number?

**Comment by abi** [comment]
It varies depending:

- which version you are on (have to send full history)
- how large your screenshot is (affects how long the output will be with max of 4096 tokens)

Here are some sample tokens and costs for GPT-4 vision.

<img width="352" alt="Screenshot 2024-04-17 at 12 33 43 PM" src="https://github.com/abi/screenshot-to-code/assets/23818/33e84492-d0cc-4b3c-be2d-3119bcf27247">

The project is definitely not optimized for token usage and there are no plans to optimize that further since the APIs are pretty cheap in general. If you're concerned about cost, we hope to support open source, local models that will be free but worse quality.

What's your budget?

**Comment by Thea1211** [comment]
> It varies depending:
> 
> * which version you are on (have to send full history)
> * how large your screenshot is (affects how long the output will be with max of 4096 tokens)
> 
> Here are some sample tokens and costs (USD) for GPT-4 vision.
> 
> <img alt="Screenshot 2024-04-17 at 12 33 43 PM" width="352" src="https://private-user-images.githubusercontent.com/23818/323306816-33e84492-d0cc-4b3c-be2d-3119bcf27247.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MDA1OTQsIm5iZiI6MTcxMzQwMDI5NCwicGF0aCI6Ii8yMzgxOC8zMjMzMDY4MTYtMzNlODQ0OTItZDBjYy00YjNjLWJlMmQtMzExOWJjZjI3MjQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDAwMzEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MzIyNGEwMzk1YTY3OTk3MDUyYWRkZGQ0ODVjZmE2YmNkYmRiN2Y2MWUwMWY4ZDZiYmQ1Y2M1NjE0MThjMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qmnCbBNCnQZMqAjj-XlYkjxGzwtVcluvlL53kwzTEVg">
> The project is definitely not optimized for token usage and there are no plans to optimize that further since the APIs are pretty cheap in general. If you're concerned about cost, we hope to support open source, local models that will be free but worse quality.
> 
> What's your budget?

I just want to get a general idea
